/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_samonkey_controller_jni_JNI */

#ifndef _Included_com_samonkey_controller_jni_JNI
#define _Included_com_samonkey_controller_jni_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_samonkey_controller_jni_JNI
 * Method:    execute
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_samonkey_controller_jni_JNI_execute
  (JNIEnv *, jclass, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
